name = "omni-ai"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[ai]
binding = "AI"

[vars]
MEDIA_URL = "https://omni-ai-media.omni-ai.workers.dev"
IMAGES_URL = "https://omni-ai-images.omni-ai.workers.dev"
AUDIO_URL = "https://omni-ai-audio.omni-ai.workers.dev"
EMBED_URL = "https://omni-ai-embeddings.omni-ai.workers.dev"

[[services]]
binding = "MEDIA_SERVICE"
service = "omni-ai-media"

[[services]]
binding = "IMAGES_SERVICE"
service = "omni-ai-images"

[[services]]
binding = "AUDIO_SERVICE"
service = "omni-ai-audio"

[[services]]
binding = "EMBED_SERVICE"
service = "omni-ai-embeddings"

[[d1_databases]]
binding = "OMNI_DB"
database_name = "mkptri-codex"
database_id = "e01ef925-3875-478f-b83e-9a5e05297c48"
