const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const ts = require("typescript");

function loadImageWorkerExports() {
  const workerPath = path.join(__dirname, "..", "..", "workers", "omni-ai-images", "src", "index.ts");
  const source = fs.readFileSync(workerPath, "utf8");
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020
    },
    fileName: "omni-ai-images-index.ts"
  }).outputText;

  const moduleRef = { exports: {} };
  const sandbox = {
    module: moduleRef,
    exports: moduleRef.exports,
    require,
    console,
    Response,
    Request,
    URL,
    TextEncoder,
    TextDecoder,
    Uint8Array,
    ArrayBuffer,
    setTimeout,
    clearTimeout,
    crypto
  };

  vm.runInNewContext(transpiled, sandbox, { filename: "omni-ai-images-index.vm.js" });
  return moduleRef.exports;
}

function expect(condition, message) {
  if (!condition) throw new Error(message);
}

function makePseudoPng(byteLength) {
  const length = Math.max(12, Number(byteLength || 12));
  const bytes = new Uint8Array(length);
  bytes[0] = 0x89;
  bytes[1] = 0x50;
  bytes[2] = 0x4e;
  bytes[3] = 0x47;
  bytes[4] = 0x0d;
  bytes[5] = 0x0a;
  bytes[6] = 0x1a;
  bytes[7] = 0x0a;
  return bytes;
}

function makeMockEnv() {
  return {
    AI: {
      async run(_model, payload) {
        const width = Number(payload?.width || 1024);
        const height = Number(payload?.height || 1024);
        if (width > 8000 || height > 8000) {
          throw new Error("model dimension limit exceeded");
        }

        const pseudoBytes = Math.max(1_200_000, Math.round(width * height * 0.18));
        return makePseudoPng(pseudoBytes);
      }
    }
  };
}

function makeAlwaysSmallEnv() {
  return {
    AI: {
      async run() {
        return makePseudoPng(120_000);
      }
    }
  };
}

function makeAlwaysLargeEnv() {
  return {
    AI: {
      async run() {
        return makePseudoPng(14_000_000);
      }
    }
  };
}

function makeProviderLimitedEnv() {
  return {
    AI: {
      async run(_model, payload) {
        const promptLength = String(payload?.prompt || "").length;
        if (promptLength > 2048) {
          throw new Error(`Length of '/prompt' must be <= 2048. got ${promptLength}`);
        }
        return makePseudoPng(1_600_000);
      }
    }
  };
}

async function run() {
  const worker = loadImageWorkerExports();
  const {
    parseResolutionFromPrompt,
    resolveDimensions,
    generateWithinSizeRange,
    handleGenerate
  } = worker;

  expect(typeof parseResolutionFromPrompt === "function", "parseResolutionFromPrompt export missing");
  expect(typeof resolveDimensions === "function", "resolveDimensions export missing");
  expect(typeof generateWithinSizeRange === "function", "generateWithinSizeRange export missing");
  expect(typeof handleGenerate === "function", "handleGenerate export missing");

  const fourK = parseResolutionFromPrompt("create a 4k cinematic image");
  expect(fourK?.width === 3840 && fourK?.height === 2160, "4k prompt should map to 3840x2160");

  const eightKVertical = parseResolutionFromPrompt("create an 8k vertical poster");
  expect(
    eightKVertical?.width === 4320 && eightKVertical?.height === 7680,
    "8k vertical prompt should map to 4320x7680"
  );

  const resolved = resolveDimensions({
    prompt: "create 8k mountain scene",
    width: 4096,
    height: 2304
  });
  expect(resolved.width === 1152 && resolved.height === 2048, "worker should use max supported 9:16 render dimensions");

  const env = makeMockEnv();
  const generated = await generateWithinSizeRange(env, {
    prompt: "create an 8k ultra detailed landscape",
    negative_prompt: "",
    seed: 42
  });

  expect(generated.bytes >= 1_048_576, `generated bytes too small: ${generated.bytes}`);
  expect(generated.bytes <= 12_582_912, `generated bytes too large: ${generated.bytes}`);
  console.log(`✓ generateWithinSizeRange: ${generated.bytes} bytes in ${generated.attempts} attempts`);

  const request = new Request("https://example.com/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      prompt: "create a 4k product hero render"
    })
  });

  const response = await handleGenerate(request, env);
  expect(response.status === 200, `expected 200 from handleGenerate, got ${response.status}`);

  const byteHeader = Number(response.headers.get("X-Omni-Image-Bytes") || 0);
  const statusHeader = String(response.headers.get("X-Omni-Image-Size-Status") || "");
  const forcedWidthHeader = Number(response.headers.get("X-Omni-Image-Forced-Width") || 0);
  const forcedHeightHeader = Number(response.headers.get("X-Omni-Image-Forced-Height") || 0);
  const dimensionLockHeader = String(response.headers.get("X-Omni-Image-Dimension-Lock") || "");

  expect(byteHeader >= 1_048_576 && byteHeader <= 12_582_912, `response header bytes out of range: ${byteHeader}`);
  expect(statusHeader === "within", `response size status should be 'within', got '${statusHeader}'`);
  expect(forcedWidthHeader === 2160, `forced width header should be 2160, got ${forcedWidthHeader}`);
  expect(forcedHeightHeader === 3840, `forced height header should be 3840, got ${forcedHeightHeader}`);
  expect(dimensionLockHeader === "strict", `dimension lock header should be 'strict', got '${dimensionLockHeader}'`);

  console.log("✓ handleGenerate response headers report 1-12MB in-range export");

  const impossibleRequest = new Request("https://example.com/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      prompt: "create a 4k render that must fail size targeting"
    })
  });

  const impossibleResponse = await handleGenerate(impossibleRequest, makeAlwaysSmallEnv());
  expect(impossibleResponse.status === 422, `expected 422 for impossible size target, got ${impossibleResponse.status}`);

  const impossibleBody = await impossibleResponse.json();
  expect(impossibleBody?.success === false, "expected success=false for impossible size target");
  expect(
    /Unable to satisfy export size range/i.test(String(impossibleBody?.error || "")),
    "expected detailed size-range failure error"
  );
  expect(impossibleBody?.details?.status === "under", "expected details.status to be 'under'");
  console.log("✓ handleGenerate returns 422 with details when size target is unattainable");

  const oversizedRequest = new Request("https://example.com/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      prompt: "create a high-detail image that must fail oversized targeting"
    })
  });

  const oversizedResponse = await handleGenerate(oversizedRequest, makeAlwaysLargeEnv());
  expect(oversizedResponse.status === 422, `expected 422 for oversized target failure, got ${oversizedResponse.status}`);

  const oversizedBody = await oversizedResponse.json();
  expect(oversizedBody?.success === false, "expected success=false for oversized target failure");
  expect(
    /Unable to satisfy export size range/i.test(String(oversizedBody?.error || "")),
    "expected detailed oversized size-range failure error"
  );
  expect(oversizedBody?.details?.status === "over", "expected details.status to be 'over'");
  console.log("✓ handleGenerate returns 422 with details when output remains oversized");

  const longPromptRequest = new Request("https://example.com/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      prompt: `create a cinematic portrait with intricate details ${"x".repeat(5000)}`
    })
  });

  const longPromptResponse = await handleGenerate(longPromptRequest, makeProviderLimitedEnv());
  expect(longPromptResponse.status === 200, `expected 200 for long prompt clamp path, got ${longPromptResponse.status}`);
  console.log("✓ handleGenerate clamps long prompts to provider-safe payload length");

  console.log("Image worker contract smoke test passed.");
}

run().catch((error) => {
  console.error("Image worker contract smoke test failed:", error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
