name = "ion-ai"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[ai]
binding = "AI"

[vars]
IMAGES_URL = "https://ion-ai-images.omni-ai.workers.dev"
AUDIO_URL = "https://ion-ai-audio.omni-ai.workers.dev"
EMBED_URL = "https://ion-ai-embeddings.omni-ai.workers.dev"

[[services]]
binding = "IMAGES_SERVICE"
service = "ion-ai-images"

[[services]]
binding = "AUDIO_SERVICE"
service = "ion-ai-audio"

[[services]]
binding = "EMBED_SERVICE"
service = "ion-ai-embeddings"

[[d1_databases]]
binding = "ION_DB"
database_name = "mkptri-codex"
database_id = "e01ef925-3875-478f-b83e-9a5e05297c48"
