/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'ion-blue': {
          50: 'var(--ix-ion-blue-50)',
          100: 'var(--ix-ion-blue-100)',
          200: 'var(--ix-ion-blue-200)',
          300: 'var(--ix-ion-blue-300)',
          400: 'var(--ix-ion-blue-400)',
          500: 'var(--ix-ion-blue-500)',
          600: 'var(--ix-ion-blue-600)',
          700: 'var(--ix-ion-blue-700)',
          800: 'var(--ix-ion-blue-800)',
          900: 'var(--ix-ion-blue-900)',
        },
        'spectral-cyan': {
          50: 'var(--ix-spectral-cyan-50)',
          100: 'var(--ix-spectral-cyan-100)',
          200: 'var(--ix-spectral-cyan-200)',
          300: 'var(--ix-spectral-cyan-300)',
          400: 'var(--ix-spectral-cyan-400)',
          500: 'var(--ix-spectral-cyan-500)',
          600: 'var(--ix-spectral-cyan-600)',
          700: 'var(--ix-spectral-cyan-700)',
          800: 'var(--ix-spectral-cyan-800)',
          900: 'var(--ix-spectral-cyan-900)',
        },
        'pine-black': {
          600: 'var(--ix-pine-black-600)',
          700: 'var(--ix-pine-black-700)',
          800: 'var(--ix-pine-black-800)',
          900: 'var(--ix-pine-black-900)',
        },
        'quantum-white': 'var(--ix-quantum-white)',
        'quantum-white-warm': 'var(--ix-quantum-white-warm)',
        'amber-signal': {
          400: 'var(--ix-amber-signal-400)',
          500: 'var(--ix-amber-signal-500)',
          600: 'var(--ix-amber-signal-600)',
        },
      },
      fontFamily: {
        'inter': 'var(--ix-font-body)',
        'mono': 'var(--ix-font-mono)',
        'display': 'var(--ix-font-display)',
      },
      spacing: {
        '0.5': 'var(--ix-space-0-5)',
        '1': 'var(--ix-space-1)',
        '1.5': 'var(--ix-space-1-5)',
        '2': 'var(--ix-space-2)',
        '3': 'var(--ix-space-3)',
        '4': 'var(--ix-space-4)',
        '6': 'var(--ix-space-6)',
        '8': 'var(--ix-space-8)',
        '12': 'var(--ix-space-12)',
        '16': 'var(--ix-space-16)',
      },
      borderRadius: {
        'sm': 'var(--ix-radius-sm)',
        'md': 'var(--ix-radius-md)',
        'lg': 'var(--ix-radius-lg)',
        'full': 'var(--ix-radius-full)',
      },
      boxShadow: {
        '1': 'var(--ix-shadow-1)',
        '2': 'var(--ix-shadow-2)',
        '3': 'var(--ix-shadow-3)',
        '4': 'var(--ix-shadow-4)',
        '5': 'var(--ix-shadow-5)',
      },
      transitionTimingFunction: {
        'sovereign': 'var(--ix-ease-sovereign)',
        'ambient': 'var(--ix-ease-ambient)',
        'grok': 'var(--ix-ease-grok)',
        'settle': 'var(--ix-ease-settle)',
      },
      transitionDuration: {
        'micro': 'var(--ix-duration-micro)',
        'quick': 'var(--ix-duration-quick)',
        'standard': 'var(--ix-duration-standard)',
        'dramatic': 'var(--ix-duration-dramatic)',
        'cinematic': 'var(--ix-duration-cinematic)',
      },
    },
  },
  plugins: [],
}