import type { StylePreset } from './types';

export const BASE_NEGATIVE_PROMPT = [
  'lowres',
  'bad anatomy',
  'bad hands',
  'text',
  'error',
  'missing fingers',
  'extra digit',
  'fewer digits',
  'cropped',
  'worst quality',
  'low quality',
  'jpeg artifacts',
  'signature',
  'watermark',
  'username',
  'blurry',
  'deformed',
  'disfigured',
  'mutation',
  'mutated',
  'extra limbs',
  'extra arms',
  'extra legs',
  'malformed limbs',
  'fused fingers',
  'too many fingers',
  'long neck',
].join(', ');

export const STYLE_PRESETS: Record<StylePreset['id'], StylePreset> = {
  cinematic_niji: {
    id: 'cinematic_niji',
    name: 'Cinematic Niji-Grade Anime',
    description: 'Dramatic lighting, vivid color, high-detail anime framing.',
    exampleThumbnail: '/images/styles/cinematic-niji.webp',
    positivePrefix: 'anime, detailed, cinematic lighting, dramatic angle, vivid colors, sharp focus, depth of field, bloom',
    negativeAdditions: 'flat colors, simple background',
    sampler: 'euler',
    steps: 28,
    cfgScale: 5.0,
    defaultResolution: { width: 1024, height: 1536 },
  },
  soft_pastel_shoujo: {
    id: 'soft_pastel_shoujo',
    name: 'Soft Pastel Shoujo',
    description: 'Dreamy pastel palette with delicate linework and soft light.',
    exampleThumbnail: '/images/styles/soft-pastel-shoujo.webp',
    positivePrefix: 'pastel colors, soft lighting, dreamy, shoujo, delicate linework, sparkles, flower motifs, ethereal',
    negativeAdditions: 'harsh shadows, dark colors, gritty, high contrast',
    sampler: 'euler',
    steps: 25,
    cfgScale: 5.5,
    defaultResolution: { width: 1024, height: 1024 },
  },
  gritty_seinen: {
    id: 'gritty_seinen',
    name: 'Gritty Seinen',
    description: 'Dark, mature anime look with contrast and muted palette.',
    exampleThumbnail: '/images/styles/gritty-seinen.webp',
    positivePrefix: 'dark atmosphere, mature, gritty, high contrast, seinen, dramatic shadows, muted colors',
    negativeAdditions: 'bright colors, cute, chibi, pastel, sparkles',
    sampler: 'euler',
    steps: 30,
    cfgScale: 6.0,
    defaultResolution: { width: 1024, height: 1536 },
  },
  retro_90s_cel: {
    id: 'retro_90s_cel',
    name: 'Retro 90s Cel-Anime',
    description: 'Classic cel-shaded anime with nostalgic VHS warmth.',
    exampleThumbnail: '/images/styles/retro-90s-cel.webp',
    positivePrefix: '1990s anime, cel shading, retro anime, vhs aesthetic, warm tones, nostalgic, film grain',
    negativeAdditions: 'digital colors, overly clean, 3d render',
    sampler: 'euler',
    steps: 25,
    cfgScale: 5.5,
    defaultResolution: { width: 1024, height: 768 },
  },
  semi_realistic_2_5d: {
    id: 'semi_realistic_2_5d',
    name: 'Semi-Realistic 2.5D',
    description: 'Anime forms with realistic lighting and surface detail.',
    exampleThumbnail: '/images/styles/semi-realistic-2-5d.webp',
    positivePrefix: 'semi-realistic, detailed skin, realistic lighting, anime eyes, detailed hair, subsurface scattering',
    negativeAdditions: 'flat, cartoon, chibi, sketch, 2d',
    sampler: 'ddim',
    steps: 30,
    cfgScale: 5.0,
    defaultResolution: { width: 1024, height: 1536 },
  },
  painterly_watercolor: {
    id: 'painterly_watercolor',
    name: 'Painterly / Watercolor',
    description: 'Traditional-media softness with visible brushwork.',
    exampleThumbnail: '/images/styles/painterly-watercolor.webp',
    positivePrefix: 'watercolor, painterly, soft edges, visible brushstrokes, traditional media, artistic',
    negativeAdditions: 'sharp lines, digital art, photorealistic, clean edges',
    sampler: 'euler',
    steps: 25,
    cfgScale: 5.5,
    defaultResolution: { width: 1024, height: 1024 },
  },
  lofi_aesthetic: {
    id: 'lofi_aesthetic',
    name: 'LoFi Aesthetic',
    description: 'Warm, cozy slice-of-life scenes with soft ambient mood.',
    exampleThumbnail: '/images/styles/lofi-aesthetic.webp',
    positivePrefix: 'lo-fi, cozy, warm lighting, evening, study vibes, headphones, slice of life, detailed background',
    negativeAdditions: 'harsh lighting, cold colors, action, fighting',
    sampler: 'euler',
    steps: 25,
    cfgScale: 5.0,
    defaultResolution: { width: 1536, height: 1024 },
  },
};

export function getStylePreset(styleId: StylePreset['id']): StylePreset {
  return STYLE_PRESETS[styleId];
}

export function listStylePresets(): StylePreset[] {
  return Object.values(STYLE_PRESETS);
}