from __future__ import annotations

from typing import Dict

from omni_ai.human.head.models import BrainRegion

BRAIN_REGIONS: Dict[str, BrainRegion] = {
    "prefrontal_cortex": BrainRegion(
        id="prefrontal_cortex",
        name="Prefrontal Cortex",
        lobe="frontal",
        hemisphere="bilateral",
        functions=["planning", "decision making", "personality"],
        connections=["motor_cortex", "limbic_system", "wernicke_area"],
    ),
    "motor_cortex": BrainRegion(
        id="motor_cortex",
        name="Primary Motor Cortex",
        lobe="frontal",
        hemisphere="bilateral",
        functions=["voluntary movement control"],
        connections=["prefrontal_cortex", "broca_area", "cerebellum"],
    ),
    "broca_area": BrainRegion(
        id="broca_area",
        name="Broca Area",
        lobe="frontal",
        hemisphere="left",
        functions=["speech production", "articulation planning"],
        connections=["motor_cortex", "wernicke_area"],
    ),
    "wernicke_area": BrainRegion(
        id="wernicke_area",
        name="Wernicke Area",
        lobe="temporal",
        hemisphere="left",
        functions=["language comprehension"],
        connections=["broca_area", "auditory_cortex"],
    ),
    "auditory_cortex": BrainRegion(
        id="auditory_cortex",
        name="Primary Auditory Cortex",
        lobe="temporal",
        hemisphere="bilateral",
        functions=["sound processing"],
        connections=["wernicke_area", "thalamus"],
    ),
    "visual_cortex": BrainRegion(
        id="visual_cortex",
        name="Primary Visual Cortex",
        lobe="occipital",
        hemisphere="bilateral",
        functions=["visual feature extraction"],
        connections=["thalamus", "parietal_cortex", "temporal_cortex"],
    ),
    "parietal_cortex": BrainRegion(
        id="parietal_cortex",
        name="Parietal Cortex",
        lobe="parietal",
        hemisphere="bilateral",
        functions=["spatial integration", "sensorimotor transformation"],
        connections=["visual_cortex", "somatosensory_cortex", "motor_cortex"],
    ),
    "temporal_cortex": BrainRegion(
        id="temporal_cortex",
        name="Temporal Cortex",
        lobe="temporal",
        hemisphere="bilateral",
        functions=["object recognition", "semantic association"],
        connections=["visual_cortex", "wernicke_area", "limbic_system"],
    ),
    "somatosensory_cortex": BrainRegion(
        id="somatosensory_cortex",
        name="Primary Somatosensory Cortex",
        lobe="parietal",
        hemisphere="bilateral",
        functions=["touch", "proprioception", "pain localization"],
        connections=["motor_cortex", "thalamus"],
    ),
    "thalamus": BrainRegion(
        id="thalamus",
        name="Thalamus",
        lobe=None,
        hemisphere="bilateral",
        functions=["sensory relay", "attention gating"],
        connections=["visual_cortex", "auditory_cortex", "somatosensory_cortex"],
    ),
    "limbic_system": BrainRegion(
        id="limbic_system",
        name="Limbic System",
        lobe=None,
        hemisphere="bilateral",
        functions=["emotion", "memory salience"],
        connections=["prefrontal_cortex", "hypothalamus"],
    ),
    "hypothalamus": BrainRegion(
        id="hypothalamus",
        name="Hypothalamus",
        lobe=None,
        hemisphere="bilateral",
        functions=["autonomic regulation", "endocrine control"],
        connections=["limbic_system", "brainstem"],
    ),
    "cerebellum": BrainRegion(
        id="cerebellum",
        name="Cerebellum",
        lobe=None,
        hemisphere="bilateral",
        functions=["motor coordination", "error correction"],
        connections=["motor_cortex", "brainstem"],
    ),
    "brainstem": BrainRegion(
        id="brainstem",
        name="Brainstem",
        lobe=None,
        hemisphere="bilateral",
        functions=["cranial nerve nuclei", "vital autonomic control"],
        connections=["cerebellum", "thalamus", "hypothalamus"],
    ),
}
